### PR TITLE
More clear error messages for invalid characters

### LINKED ISSUE #32: camelCase keys throw exception: IllegalArgumentException: Missing closing brace: }
keyCamelCase -> fails
key_camel_case -> accepted

### LINKED ISSUE #34: Numbers in keys throw exception: IllegalArgumentException: Missing closing brace: }
Looks like this it's caused by only checking for letters and underscores in 

```
private KeyToken key(Token prev){

....

    while ((curChar >= 'a' && curChar <= 'z') || curChar == '_') {
      sb.append(curChar);
      consume();
    }

...
}
```

### PR DESCRIPTION
**Pull request by pforhan**
Tweaks invalid start- and end-of-token messages for clarity.

Inspired by #33, fixes #32 and fixes #34, probably #29 as well.

### CODE REVIEW

**Comment by pforhan** [comment]
Not sure what's up with the CI build, a `./gradlew clean build` comes back successful for me.

**Comment by pforhan** [comment]
` failed to find target with hash string 'android-23' in: /usr/local/android-sdk`

**Comment by zach-klippenstein** [comment]
LGTM 👌

**Comment by pforhan** [comment]
Pushed a small change to help users differentiate the first-character message from the error later on.

**Comment by pforhan** [comment]
@JakeWharton @rjrjr @loganj anyone interested in merging this?

**Comment by rjrjr** [comment]
LGTM, but can we figure out why the Travis is failing?

**Comment by pforhan** [comment]
Interesting: android-23 is listed on https://docs.travis-ci.com/user/languages/android -- though that could just be out of date.

**Comment by pforhan** [comment]
I think this is it:
> Package Android SDK Platform-tools, revision 26 not installed due to rejected license 'android-sdk-license-c81a61d9'.

**Comment by pforhan** [comment]
That passed.  Pushed a small formatting fix for the .travis.yml file

**Comment by pforhan** [comment]
Sigh, and another -- I added the newline to the wrong place

**Comment by pforhan** [comment]
Green!

**Comment by pforhan** [comment]
Can I get a merge here?  I think this is a good usability improvement that will head off more issues like #36

**Pull request merged**
