### PR TITLE
Add support Camel Case for key to avoid crash

### PR DESCRIPTION
**Pull request by vsay01**
Hopefully it support the camel case for the key

### CODE REVIEW

**Comment by pforhan** [comment]
You'd have to adjust tests, too.  For what it's worth, there's already #35 that clarifies the error messages.

**Comment by vsay01** [comment]
@pforhan It seems test case illegalTokenCharactersFailFast will fail if we use Camel Case for the token. Is it something that the library want to? 
For my case, i need to have Camel Case that's why I thought it would be useful for others as well. Would love to hear the direction from you, I can either close this PR or fix the unit test. Thanks

**Comment by vsay01** [comment]
For now I fix the unit tests in my local branch, and all the test cases are passed.
If the library want to support the Upper case then I will make the following commit so that the build pass.

```
   //commented out this test case to support if want to support Upper Case
   /*@Test public void illegalTokenCharactersFailFast() {
      try {
        from("blah {NoUppercaseAllowed}");
        fail("Expected IllegalArgumentException");
      } catch (IllegalArgumentException e) {
      }
    }*/

    @Test
    public void tokenCanHaveUpperCase() {
        assertThat(from("blah {UppercaseAllowed}").put("UppercaseAllowed", "Uppercase Allowed").format().toString()).isEqualTo(
                "blah Uppercase Allowed");
    }
```

**Comment by pforhan** [comment]
If you look at the issue history (like #9) , there's not been a lot of desire for it, that's why I beefed up the error messages and tests to be more explicit about the expected key format.

**Comment by vsay01** [comment]
@pforhan  Thanks for the information. I will close this pull request as the library won't support the Upper case as the choice of the library as mentioned in #9.
For all who need support for upper case, you can find Fixes #17  provided the fix or visit my [forked repo.](https://github.com/vsay01/phrase) . 
i planned to support as well:

`#{token}`

Thanks for the library.

**Pull request closed without merging**
